parameters:
#    brainstrap_bundles_front.example.class: Brainstrap\Bundles\FrontBundle\Example

services:
#    brainstrap_bundles_front.example:
#        class: %brainstrap_bundles_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
