object_objecttype:
    path:     /
    defaults: { _controller: "BrainstrapBundlesFrontBundle:Object\ObjectType:index" }

#object_objecttype_show:
#    path:     /{id}/show
#    defaults: { _controller: "BrainstrapBundlesFrontBundle:Object\ObjectType:show" }

object_objecttype_new:
    path:     /new
    defaults: { _controller: "BrainstrapBundlesFrontBundle:Object\ObjectType:new" }

object_objecttype_create:
    path:     /create
    defaults: { _controller: "BrainstrapBundlesFrontBundle:Object\ObjectType:create" }
    requirements: { _method: post }

object_objecttype_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrainstrapBundlesFrontBundle:Object\ObjectType:edit" }

object_objecttype_update:
    path:     /{id}/update
    defaults: { _controller: "BrainstrapBundlesFrontBundle:Object\ObjectType:update" }
    requirements: { _method: post|put }

object_objecttype_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrainstrapBundlesFrontBundle:Object\ObjectType:delete" }
    requirements: { _method: post|delete }
